const config = {
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  API_KEY: process.env.NEXT_PUBLIC_API_KEY,
  API_SECRET: process.env.NEXT_PUBLIC_API_SECRET,
  API_TOKEN: process.env.NEXT_PUBLIC_API_TOKEN,
  API_TOKEN_SECRET: process.env.NEXT_PUBLIC_API_TOKEN_SECRET,
  API_CONSUMER_KEY: process.env.NEXT_PUBLIC_API_CONSUMER_KEY,
  API_CONSUMER_SECRET: process.env.NEXT_PUBLIC_API_CONSUMER_SECRET,
  API_ACCESS_TOKEN: process.env.NEXT_PUBLIC_API_ACCESS_TOKEN,
  API_ACCESS_TOKEN_SECRET: process.env.NEXT_PUBLIC_API_ACCESS_TOKEN_SECRET,
};

export default config;